const menu = [
    {
      id: 1,
      title: 'ESPRESSO',
      category: 'TOPLI NAPICI',
      price: 1.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'DOMAĆA KAFA',
      category: 'TOPLI NAPICI',
      price: 1.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 3,
      title: 'NESS',
      category: 'TOPLI NAPICI',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 4,
      title: ' KAPUĆINO',
      category: 'TOPLI NAPICI',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    }, 
    {
      id: 5,
      title: 'ČAJ',
      category: 'TOPLI NAPICI',
      price: 1.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 6,
      title: 'VIVIA',
      category: 'BEZALKOHOLNA PIĆA',
      price: 1.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 7,
      title: 'VIVIA LIMETA',
      category: 'BEZALKOHOLNA PIĆA',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 8,
      title: 'KISELA VODA',
      category: 'BEZALKOHOLNA PIĆA',
      price: 1.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 9,
      title: 'EXOTIC',
      category: 'BEZALKOHOLNA PIĆA',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 10,
      title: 'LEDENI ČAJ',
      category: 'BEZALKOHOLNA PIĆA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 11,
      title: 'CAPPY',
      category: ' SOKOVI',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 12,
      title: 'VOĆNI SOKOVI',
      category: ' SOKOVI',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 13,
      title: 'SOLA',
      category: ' SOKOVI',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 14,
      title: 'COCA COLA',
      category: ' SOKOVI',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 15,
      title: 'SCHWEPPS',
      category: ' SOKOVI',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 16,
      title: 'SPRITE',
      category: ' SOKOVI',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 17,
      title: 'FANTA',
      category: ' SOKOVI',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 18,
      title: 'LIMUNADA',
      category: ' SOKOVI',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 19,
      title: 'CJEĐENA NARANDŽA',
      category: ' SOKOVI',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 20,
      title: 'CEDEVITA',
      category: ' SOKOVI',
      price: 1.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 21,
      title: 'REDBULL',
      category: ' ENERGETSKA PIĆA',
      price: 5.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 22,
      title: 'GUARANA',
      category: ' ENERGETSKA PIĆA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 23,
      title: 'RICHARD',
      category: ' ENERGETSKA PIĆA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 24,
      title: 'TAMJANIKA O.7L',
      category: 'VINA',
      price: 25.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 25,
      title: 'VRANAC O.7L',
      category: 'VINA',
      price: 20.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 26,
      title: 'VRANAC O.187L',
      category: 'VINA',
      price: 5.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 27,
      title: 'KRSTAČ O.187L',
      category: 'VINA',
      price: 5.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 28,
      title: 'KUPINOVO VINO O.187L',
      category: 'VINA',
      price: 5.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 29,
      title: 'ČAŠA BIJELOG VINA',
      category: 'VINA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 30,
      title: 'ČAŠA CRNOG VINA',
      category: 'VINA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 31,
      title: 'SOMERSBY',
      category: 'PIVA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 32,
      title: 'HEINEKEN',
      category: 'PIVA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 33,
      title: 'BEZALKOHOLNO PIVO',
      category: 'PIVA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 34,
      title: 'TUBORG',
      category: 'PIVA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 35,
      title: 'BAVARIA',
      category: 'PIVA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 36,
      title: 'ZAJEČARSKO',
      category: 'PIVA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 37,
      title: 'JELEN',
      category: 'PIVA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 38,
      title: 'JACK DANIELS 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 5.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 39,
      title: 'RED LABEL 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 3.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 40,
      title: 'SMIRNOFF 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 41,
      title: 'JEGER 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 3.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 42,
      title: 'GIN GORDON`S 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 43,
      title: 'TEKILA 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 44,
      title: 'STOCK 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 45,
      title: 'GORKI LIST 0,03L',
      category: 'ŽESTOKA PIĆA',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 46,
      title: 'BELVEDERE 0,7L',
      category: 'ŽESTOKA PIĆA',
      price: 140.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 47,
      title: 'KAJSIJA',
      category: 'RAKIJA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 48,
      title: 'DUNJA',
      category: 'RAKIJA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 49,
      title: 'VILJAMOVKA',
      category: 'RAKIJA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 50,
      title: 'BABA VIŠNJA',
      category: 'RAKIJA',
      price: 2.50,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 51,
      title: 'MEDUŠKA',
      category: 'RAKIJA',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 52,
      title: 'ŠLJIVA',
      category: 'RAKIJA',
      price: 2.00,
      img: './images/item-1.jpeg',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },

    




    
    
  ];
  export default menu;
  



